package com.escom.modelo;
// Generated 17/06/2015 02:09:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MovArticulo generated by hbm2java
 */
public class MovArticulo  implements java.io.Serializable {


     private Integer idmovimiento;
     private Articulo articulo;
     private Date fecha;
     private char tipo;
     private String cantidad;

    public MovArticulo() {
    }

    public MovArticulo(Articulo articulo, Date fecha, char tipo, String cantidad) {
       this.articulo = articulo;
       this.fecha = fecha;
       this.tipo = tipo;
       this.cantidad = cantidad;
    }
   
    public Integer getIdmovimiento() {
        return this.idmovimiento;
    }
    
    public void setIdmovimiento(Integer idmovimiento) {
        this.idmovimiento = idmovimiento;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


